### ISSUE TITLE
out of curiosity, why the switch to wezterm?

### ISSUE THREAD

**Issue by luxus** [abzcoding/wezterm#1]
i tried it myself and cannot remember why I did go back to kitty.
any reason why u did the switch to wezterm?
maybe because its written in rust?
i found no better way to talk to you :D 
u didn't accept my discord friendrequest :D

**Comment by abzcoding** [comment]
Oh hi, yeah, sorry I'm not gonna be on discord for a while, 
I just wanted to compare wezterm and kitty :)
